services:
  db:
    image: postgres:18
    container_name: nido-db
    environment:
      POSTGRES_USER: minime
      POSTGRES_PASSWORD: minime
      POSTGRES_DB: minime
    ports:
      - 5174:5432
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db:/var/lib/postgresql
    restart: unless-stopped
    shm_size: 128mb
  keycloak:
    image: keycloak/keycloak:26.7
    container_name: nido-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: minime
      KC_DB_PASSWORD: minime
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
    ports:
      - 5175:8080
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import
    depends_on:
      - db
    restart: unless-stopped
    command: start-dev --import-realm
volumes:
  db:
